### ISSUE TITLE
Additional Feature: Table select

### ISSUE THREAD

**Issue by jgreth** [vertexvaar/logs#4]
Hi nice Extension. I would like to have an option to select the tables, the logs are shown from.
This would be handy when using own log tables.

**Comment by vertexvaar** [comment]
Hi @jgreth 

i thought this is a rather simple feature, but integrating it into the extension is a rather huge task since it conflicts with an other feature, which allows extension authors to integrate the log reading functionality (by extending the controller) in their own extension (backend module) and their log configuration only.

I really appreciate your proposal and added it to the feature list, but i'm sorry i can't implement this yet.

As an alternative you can use the `component` filter, which btw uses wildcards. So if you want to show only logs from your ext you can add your first two namespace parts here (dot separated) and you will only see logs from that extension.

With regards

**Comment by jgreth** [comment]
Hey!
Thanks for your Wildcard Component hint. That works quite good for me. Perhaps it should be written into the docs as a possibility? 
 Thanks for your help!

**Comment by vertexvaar** [comment]
Hi @jgreth 

good point, i will record that!
